### ISSUE TITLE
Add index.html to OLW

### ISSUE THREAD

**Issue by paulvickers** [mcolburn/durham#76]
Have removed some residual issues in the html:

- incorrect domains in left and right cells leading to wrong language appearing in some cells
- removed remaining 'hymn' classes and replaced with 'dialog'

Ready to push over to OLW now.

**Comment by mcolburn** [comment]
Updated in OLW.  Please verify. If it has the changes you made, please close the issue.

**Comment by paulvickers** [comment]
Seems to be fine (I can edit using the new template) but the generation is stuck on 'retrieving'.

**Comment by paulvickers** [comment]
Wondering if I've introduced a syntax error as I can generate services using the regular DL template.

**Comment by paulvickers** [comment]
I found some unmatched `<span>` elements and one unterminated `<tr>`. Can you push the new version please?
