### ISSUE TITLE
Consider Switching to Pure OSLW Solution

### ISSUE THREAD

**Issue by mcolburn** [mcolburn/durham#78]
Paul--I sent you an email on this topic, but on your end, Office 356 rejected it as span and sent it back to me.  So, I am using this issue as another way to communicate with you.

I do not recall our original conversation when you contacted me, but I am sure I suggested using OLW and modifying an html file to trick OLW into giving you a latex file you could work with.  The back door solution I proposed is obviously problematic, both from the challenge of hand modifying an html file and OLW being able to handle the additions properly.  We are not using OLW as intended.

So, I am thinking, until Doxa is ready for public release and can output latex for the PDF generation, it might be better for you to use the original OSLW solution.  

In the mcolburn/durham project, I have created a folder called oslw.  In it I have placed a zip that has the OSLW (latex) files to generate up to three languages side-by-side to produce the Red liturgy book.  (I think it is the Red, not the Blue, but I could be wrong).

I have also put into the folder a PDF I generated this morning.

In order to provide a means for Presbytera to enter the Romanian and Russian, you could write a program to read the en_us_lash resource files (in the attached zip) and output a tab delimited file.  The columns would be Topic-Key, en_us_lash, ro_uk_dur, rus_uk_dur, e.g.

<img width="500" alt="image" src="https://github.com/mcolburn/durham/assets/1334217/6be86c42-3d16-4830-95b2-e9aef7dae98f">

Then, you could load it into a spreadsheet on Google Docs and give Presbytera access to fill in the Romanian and Russian.

When she is finished, you can export the spreadsheet to a tab delimited file, then write a program to convert each row to the appropriate OSLW format, e.g.

```
\itId{en}{uk}{lash}{prayers}{res04}{
Amen.
}%
\itId{ro}{uk}{dur}{prayers}{res04}{
Amin.
}%
\itId{rus}{uk}{dur}{prayers}{res04}{
Аминь
}%
```

What are your thoughts?

**Comment by paulvickers** [comment]
Thanks for all your efforts. I have just pushed another index.html which 1) fixes the mismatched left/right cell problem and 2) changed en_UK_durlash to en_US_goa on line 156 which is the key rubrical_en_US_goa|BeginLiturgy. Do you think it's worth trying this first? We were so close to it being finished. If not, I'll take a look at the proposed OSLW solution and see how feasible it will be.

**Comment by paulvickers** [comment]
Hi Michael

Not sure why it should bounce suddenly. Microsoft does that sometimes. ☹

I’ve replied in the issue on gitlab.

paul

**Comment by paulvickers** [comment]
Thanks for the help with this.
