### ISSUE TITLE
Pushed amended HTML

### ISSUE THREAD

**Issue by paulvickers** [mcolburn/durham#81]
Removed the books/sources preamble

**Comment by paulvickers** [comment]
Removed copyright notice

**Comment by paulvickers** [comment]
Removed horizontal rule at top as well

**Comment by paulvickers** [comment]
Removed actor directive

**Comment by paulvickers** [comment]
Removed further entries from the end of the service.

**Comment by paulvickers** [comment]
Edits to structure. Added doxastica at start and end of first antiphon; moved final part of Cherubic hymn; added new keys for [ and ] brackets to allow marking of optional sections.

**Comment by mcolburn** [comment]
Glad to assist!
